### ISSUE TITLE
unexpected keyword argument 'choice'

### ISSUE THREAD

**Issue by orctyr** [caozhichongchong/arg_ranker#1]
Hi,

I had installed arg_ranker succesfully including requirements.
But there is something error when I try test data.

Details:

$ arg_ranker -i $path/arg_ranker/test -kkdbtype standard -kkdb $path/arg_ranker/db/k2_standard_20210517/
------------------------------------------------------------------------
arg_ranker evaluates the risk of ARGs in genomes/metagenomes
Requirement: blast, diamond, kraken, python 3
Optimal: a table of the metadata of your samples (see example/All_sample_metadata.txt).
Copyright:An-Ni Zhang, MIT; Prof. Tong Zhang, University of Hong Kong
Contact caozhichongchong@gmail.com
------------------------------------------------------------------------

Traceback (most recent call last):
  File "$path/arg_ranker/bin/arg_ranker", line 8, in <module>
    sys.exit(main())
  File "$path/arg_ranker/lib/python3.8/site-packages/arg_ranker/__main__.py", line 64, in main
    optional.add_argument('-kkdbtype',
  File "$path/arg_ranker/lib/python3.8/argparse.py", line 1368, in add_argument
    action = action_class(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'choice'

Could you please give some suggestions?
Many thanks.
orctyr

**Comment by JorgeQL** [comment]
Hello,

I obtained the same error message when I tried to run the command line. Could you please help us?

Many thanks,

Jorge

**Comment by caozhichongchong** [comment]
Hi orctyr and Jorge,

Thank you so much for reaching out!
Sorry about this late reply.

I have adjusted and updated the code.
Please re-install the newest arg_ranker (v2.8.3) by running
_pip uninstall arg_ranker
pip install arg_ranker_ 

Thank you again!

Best regards,
Anni

**Comment by caozhichongchong** [comment]
Hi orctyr and Jorge,

I have noticed an error of arg_ranker.v2 when reporting the total ARG abundance in metagenomes.
If the total ARG abundance is used in your research, please refer to https://github.com/caozhichongchong/arg_ranker for more details!
I'm really sorry about this inconvenience!
Please feel free to reach out to me if you have any questions.

Best regards,
Anni

**Comment by orctyr** [comment]
Thank you very much.

**Comment by JorgeQL** [comment]
Dear Anni,
Thank you for your reply!
Best regards,

Jorge
Jor
