### ISSUE TITLE
arg_ranker analyze metagenomic paired-end sequencing files

### ISSUE THREAD

**Issue by LeabaeL** [caozhichongchong/arg_ranker#14]
Hello Anni,

Your arg_ranker software is very practical and convenient, but I encountered some problems when analyzing metagenomic data.

Since I want to analyze at the reads level, I directly followed the instructions in the help document and put the quality-controlled sequencing files in the same folder as the input files.

However, in the output file, the results of paired-end sequencing files are calculated separately, so I want to know if metagenomic data cannot be directly analyzed at the reads level for the time being.

Best regards!
LeabaeL

**Comment by caozhichongchong** [comment]
Hi LeabaeL,

Thank you for reaching out!

Great question!
Currently, the arg_ranker treats each paired-end file as an independent sample, which means it doesn't merge the results based on the pairing information.
However, there is a possible workaround that you can try. You can explore the "_search_output/Yoursample_1.fastq.blast.txt.filter_" and "_search_output/Yoursample_2.fastq.blast.txt.filter_" files, extract the IDs of the reads, and then compare them to identify pairs. By doing so, you can filter for ARGs that are supported by both reads in the pair, or conduct other read-level analysis.

Please let me know if that's what you want to do. 
I'm happy to discuss it further :)

Best regards,
Anni
