### ISSUE TITLE
problems to use the arg_ranker

### ISSUE THREAD

**Issue by diego00012138** [caozhichongchong/arg_ranker#17]
Hi,
  I get some problems to use the arg_ranker:
  1)can i just input the ORF - the results form Prodigal - instead of the raw sequence reads for paierd-end datas, would it influence the results?
  2)while using MicrobeCensu to compute the abundance of ARGs as copy number of ARGs per bacterial cell, dose "per bacterial cell" mean "genome equivalents"?
Sincerely

**Comment by caozhichongchong** [comment]
Hi,

Thank you for reaching out!
1) It is possible to get ARG risk results by inputting ORF nucleotide sequences, although it does not estimate copies per bacterial cell for the sample.
2) Good questions!  Indeed, MicrobeCensus computes "genome equivalents," not "biological bacterial cells".

Please feel free to contact me if you have any further questions.

Best regards,
Anni

**Comment by diego00012138** [comment]
Hi
   Thanks for your answer and you are so kind, but I maybe not explain my asking correctly. The first question is about the closed issue #14, is the method you recommend the best way to solve the “two answers” problem for paired end data? The second question is that I get confused with the relationship between "genome equivalents” and "biological bacterial cells".As the readme for MicrobeCensus ,it can only get the former,and the word“MicrobeCensus ”present in the compute for args per bacteria cell, I just want to know the intermediate process. Somewhere I get this “If we assume that a cell is a genome, then the genomic equivalent is equivalent to the cellular equivalent” does it is the intermediate process，I guess?
Sincerely

**Comment by caozhichongchong** [comment]
Oops, I have missed your message!
1) Yes, it would - because Kraken2 and MicrobeCensus depend on DNA sequences from whole bacterial genomes.
2) I think you're correct - "If we assume that a cell equals a genome, then the genomic equivalent is equivalent to the cellular equivalent."
Thank you for clarifying your questions!
