### ISSUE TITLE
Some problem about running arg_ranker

### ISSUE THREAD

**Issue by Songfengl** [caozhichongchong/arg_ranker#19]
I am writing to express my appreciation for the powerful and user-friendly ARG_ranker tool. It has been instrumental in my research, and I am genuinely impressed with its capabilities. However, I have recently encountered an issue when using the software due to problems with my local server.
Specifically, whenever ARG_ranker calls BLAST during its execution, the system crashes or becomes unresponsive, rendering the tool unusable. I suspect that the issue is related to memory constraints or compatibility problems with BLAST on my server.
Given the situation, I would like to inquire whether DIAMOND can be used as a replacement for BLAST within ARG_ranker. If so, could you please provide guidance on how to configure or modify ARG_ranker to utilize DIAMOND instead of BLAST for sequence alignment?
Thank you for your time and assistance. I greatly value your support and look forward to your response.

**Comment by caozhichongchong** [comment]
Hi,

Thank you for reaching out!

It would be quite tricky to replace BLAST with DIAMOND. 
You would need to modify all commands in `arg_ranker/__main__.py` that use `blastx` (e.g., lines 248, 309, and 311) to `diamond blastx` (see line 274 as an example). 
Please make sure the results file names remain unchanged.  

Please note that the results would not be as accurate.

I would recommend first trying to get BLAST to work.
It might be helpful to download the latest BLAST [here](https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/).

Good luck!
Anni
