### ISSUE TITLE
we haven't finder the database  all_KO30.pro.fasta

### ISSUE THREAD

**Issue by liaohu1231** [caozhichongchong/arg_ranker#2]
Opening the database file... No such file or directory
 [0.125s]
Error: Error opening file /public3/home/sc52870/miniconda3/lib/python3.8/site-packages/arg_ranker-2.8.1-py3.8.egg/arg_ranker/data/all_KO30.pro.fasta
Please run 
sh /public3/home/sc52870/25_metagenome/R17/arg_ranking/script_output//arg_ranker.sh

**Comment by caozhichongchong** [comment]
Hi,

Thank you so much for reaching out!
Sorry about this late reply.

Please re-install the newest arg_ranker (v2.8.3) by running
_pip uninstall arg_ranker
pip install arg_ranker_

If it doesn't work, please contact me (anniz44@mit.edu). 
Thank you again!

Best regards,
Anni

**Comment by caozhichongchong** [comment]
Hi,

I have noticed an error of arg_ranker.v2 when reporting the total ARG abundance in metagenomes.
If the total ARG abundance is used in your research, please refer to https://github.com/caozhichongchong/arg_ranker for more details!
I'm really sorry about this inconvenience!
Please feel free to reach out to me if you have any questions.

Best regards,
Anni
