### ISSUE TITLE
Can the files from the pipeline ARGs_OAP V2.0 directly be used in arg_ranker?

### ISSUE THREAD

**Issue by chunxiao-dcx** [caozhichongchong/arg_ranker#3]
Dear authors:
        Can the files from the pipeline ARGs_OAP V2.0 directly be used in arg_ranker? We found some related describtion in the previous version.
"3. Run\
`arg_ranker -f True -fo output_dir`\
`arg_ranker -i formated_table.normalize_cellnumber.gene.tab -m metadata.txt`
"
But the command could not be found in the new version. and it is quite blurry. 
When we tried to use"arg_ranker -i extracted.fa.normalize_cellnumber.gene.txt -m meta_data_online.txt",
blank result was out put

**Comment by caozhichongchong** [comment]
Hi,

Thank you for your question.
No, arg_ranker only works for ARGs_OAP V1.0.

The previous version was designed as a downstream analysis for ARGs_OAP V1.0.
The newest version incorporated ARGs_OAP V1.0 into arg_ranker, directly evaluating ARG risk based on sequences.

Hope it helps!

Best regards,
Anni

**Comment by caozhichongchong** [comment]
Hi,

I have noticed an error of arg_ranker.v2 when reporting the total ARG abundance in metagenomes.
If the total ARG abundance is used in your research, please refer to https://github.com/caozhichongchong/arg_ranker for more details!
I'm really sorry about this inconvenience!
Please feel free to reach out to me if you have any questions.

Best regards,
Anni

**Comment by chunxiao-dcx** [comment]
您好，您的邮件已收到，会尽快给您回复的~ 谢谢。
