### ISSUE TITLE
python error with example data

### ISSUE THREAD

**Issue by suskraem** [caozhichongchong/arg_ranker#5]
I downloaded and installed the newest version of arg_ranker (2.8.7) but encounter the following python error when trying to run it with the example files. While the intermediate files are created, the final Sample_ranking_results.txt table is only populated with NaNs and 0s. python 3.9 is installed. Any help is greatly appreciated!

[susanne@biol-dwalsh-cluster Desktop]$ python /opt/python39/lib/python3.9/site-packages/arg_ranker/bin/Filter.MG.py --g F -i /export/home/susanne/OldDesktop/susanne/Desktop/arg_ranking/search_output/ -f /export/home/susanne/OldDesktop/susanne/Desktop/arg_ranking/search_output/WEE300_all-trimmed-decont_1.fastq.blast.txt -db /opt/python39/lib/python3.9/site-packages/arg_ranker/data/SARG.db.fasta -dbf 2 -s 1 --ht 75 --id 80 --e 1e-07
Traceback (most recent call last):
 File “/opt/python39/lib/python3.9/site-packages/arg_ranker/bin/Filter.MG.py”, line 125, in <module>
  DB_length = Calculate_length(args.db)
 File “/opt/python39/lib/python3.9/site-packages/arg_ranker/bin/Filter.MG.py”, line 59, in Calculate_length
  except (IOError,FileNotFoundError):
NameError: global name ‘FileNotFoundError’ is not defined

**Comment by caozhichongchong** [comment]
Hi,

Thank you for reaching out!

It sounds to me that arg_ranker was using python 2 instead of python 3.9.
Could you please check it for me?
_python --version_

Best regards,
Anni

**Comment by suskraem** [comment]
Hi Anni,
thanks. You were right. I switched to a virtual env to make sure it finds the right version and now it runs. I noticed a small bug: when running the example as is, one of the  scripts is looking for the SARG.db.length file without the .txt extension
PermissionError: [Errno 13] Permission denied: ‘/opt/python39/lib/python3.9/site-packages/arg_ranker/data/SARG.db.fasta.length
However, when I change the file name correspondingly, you later encounter the error 
FileNotFoundError: [Errno 2] No such file or directory: ‘/opt/python39/lib/python3.9/site-packages/arg_ranker/data/SARG.db.fasta.length.txt
So two scripts are looking for two slightly differently named versions of the same file (but only the *.txt version is included in the repository. Best,
Susanne

**Comment by caozhichongchong** [comment]
Hi Susanne,

Sorry about that and thank you for letting me know!
I have made them consistent and uploaded the new version.

Please let me know if there's any other problems!
Thank you again!

Best regards,
Anni

**Comment by caozhichongchong** [comment]
Hi Susanne,

I have noticed an error of arg_ranker.v2 when reporting the total ARG abundance in metagenomes.
If the total ARG abundance is used in your research, please refer to https://github.com/caozhichongchong/arg_ranker for more details!
I'm really sorry about this inconvenience!
Please feel free to reach out to me if you have any questions.

Best regards,
Anni
