### ISSUE TITLE
Suspicious error of ARG_table.sum.py

### ISSUE THREAD

**Issue by susutBu** [caozhichongchong/arg_ranker#6]
Hi Anni:
Thanks for your greate tool.  I can't find the data files stored in the example folder. So I tested it using my data, but there is something error when calling ARG_table.sum.py, and maybe caused by the incorrect file name in line 32 of ARG_table.sum.py. I fixed it and it worked.
details:  I changed "`for lines in open(args.d.replace('.structure.txt','.db.fasta.length'),'r'):`"  by "`for lines in open(args.d.replace('.structure.txt','.db.fasta.length.txt'),'r'):`"
So, FYI.

![image](https://user-images.githubusercontent.com/42882120/161432755-3ccbd08a-40aa-46fd-a5b9-61cc8845fdff.png)

**Comment by caozhichongchong** [comment]
Hi,

Sorry about that and thank you for letting me know!
This [issue](https://github.com/caozhichongchong/arg_ranker/issues/5) was reported and resolved with a new pip version uploaded.

Best regards,
Anni

**Comment by caozhichongchong** [comment]
Hi,

I have noticed an error of arg_ranker.v2 when reporting the total ARG abundance in metagenomes.
If the total ARG abundance is used in your research, please refer to https://github.com/caozhichongchong/arg_ranker for more details!
I'm really sorry about this inconvenience!
Please feel free to reach out to me if you have any questions.

Best regards,
Anni
