### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by yenjh3910** [caozhichongchong/arg_ranker#7]
I ran arg_ranker pipeline, and got error in "ARG_table.sum.py" step.
This is the command I used:
`arg_ranker -i arg_ranker_test -kkdb ~/kraken_db -t 16 -o arg_ranker_output`
`sh /home/yen/arg_ranker_output/script_output//arg_ranker.sh`

Reported 6171 pairwise alignments, 6171 HSPs.
6171 queries aligned.
Loading database information... done.
37443608 sequences (5648.90 Mbp) processed in 2652.129s (847.1 Kseq/m, 127.80 Mbp/m).
  13759224 sequences classified (36.75%)
  23684384 sequences unclassified (63.25%)
Traceback (most recent call last):
  File "/home/yen/miniconda3/lib/python3.8/site-packages/arg_ranker/bin/ARG_table.sum.py", line 92, in <module>
    sum_ARG(allsearchoutput)
  File "/home/yen/miniconda3/lib/python3.8/site-packages/arg_ranker/bin/ARG_table.sum.py", line 40, in sum_ARG
    ARG_length = load_ARG_length()
  File "/home/yen/miniconda3/lib/python3.8/site-packages/arg_ranker/bin/ARG_table.sum.py", line 34, in load_ARG_length
    ARG,ARG2,genelength = lines_set[0:3]
ValueError: not enough values to unpack (expected 3, got 2)

How could I fix it, thanks a lot

**Comment by caozhichongchong** [comment]
Hi,

I have noticed an error of arg_ranker.v2 when reporting the total ARG abundance in metagenomes.
If the total ARG abundance is used in your research, please refer to https://github.com/caozhichongchong/arg_ranker for more details!
I'm really sorry about this inconvenience!
Please feel free to reach out to me if you have any questions.

Best regards,
Anni
