### ISSUE TITLE
comparing arg-ranker v2 and v3

### ISSUE THREAD

**Issue by suskraem** [caozhichongchong/arg_ranker#8]
Hello,
I re-ran the last two commands of my arg_ranker v2 run with arg_ranker v3 as instructed. However, when I compare the output files they are identical to the earlier version (including the total abundance). Are there any instances in which you would not expect any change? Where exactly should I be seeing a difference? I just want to make sure I'm reporting correct results! Thanks!

**Comment by caozhichongchong** [comment]
Hi,

Thank you for reaching out!

Did you run the last two commands with this new [ARG_table.sum.py](https://github.com/caozhichongchong/arg_ranker/tree/v2.0/arg_ranker/bin_v2only/ARG_table.sum.py)?
This [ARG_table.sum.py](https://github.com/caozhichongchong/arg_ranker/tree/v2.0/arg_ranker/bin_v2only/ARG_table.sum.py) is meant for fixing arg_ranker.v2 and the results of arg_ranker.v2.
Please do not replace ARG_table.sum.py in arg_ranker.v3 with this [ARG_table.sum.py](https://github.com/caozhichongchong/arg_ranker/tree/v2.0/arg_ranker/bin_v2only/ARG_table.sum.py).

Please let me know if the new results are still the same. 
Hope it helps!

I have made it clearer in the README thanks to your question :)

Best regards,
Anni
